{
  "limits": {
    "elements": [
      {
        "max": {
          "effort": 0.0,
          "position": 1.0471975803375244,
          "speed": 0.0
        },
        "min": {
          "position": 0.0
        }
      },
      {
        "max": {
          "effort": 0.0,
          "position": 3.140000104904175,
          "speed": 0.0
        },
        "min": {
          "position": -3.140000104904175
        }
      },
      {
        "max": {
          "effort": 0.0,
          "position": 3.140000104904175,
          "speed": 0.0
        },
        "min": {
          "position": -3.140000104904175
        }
      }
    ],
    "names": [
      "1_link_joint",
      "2_link_joint",
      "3_link_joint"
    ]
  }
}