services:
  rover:
    image: "rover"
    container_name: "rover-container"
    network_mode: "host"
    privileged: true
    ports:
      - "24650-24651" # Using DOMAIN_ID=69 calculated here: https://docs.ros.org/en/galactic/Concepts/About-Domain-ID.html
      - "24660-24690"
    environment:
      - ROS_DOMAIN_ID=69
    entrypoint: /home/robotics/Rover/entrypoint
    restart: "unless-stopped"

# https://superuser.com/questions/360336/differentiate-between-identical-usb-devices-on-linux

# sudo docker compose -f docker/compose.yml run rover
