services:
  rover:
    image: "rover"
    stdin_open: true  # Run in interactive mode. Not necessary for the rover, but useful for debugging
    tty: true         # ^^^
    network_mode: "host"
    privileged: true
    ports:
      - "24650-24651" # Using DOMAIN_ID=69 calculated here: https://docs.ros.org/en/galactic/Concepts/About-Domain-ID.html
      - "24660-24690"

    
    environment:
      - ROS_DOMAIN_ID=69
    entrypoint: /home/robotics/Rover/entrypoint

# sudo docker compose -f docker/compose.yml run rover
