services:
  rover:
    image: "rover"
    build: ..
    stdin_open: true  # Run in interactive mode. Not necessary for the rover, but useful for debugging
    tty: true         # ^^^
    ports:
      - "24650:24651" # Using DOMAIN_ID=69 calculated here: https://docs.ros.org/en/galactic/Concepts/About-Domain-ID.html
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0" # Allow the container to access the Serial USB
      - "/dev/ttyUSB0:/dev/ttyUSB0" # Allow the container to access the USB port
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}