services:
  uirover:
    image: "ethanholter/uirover"
    container_name: "rover-container"
    network_mode: "host"
    privileged: true
    environment:
      - ROS_DOMAIN_ID=69
      - ROS_DISCOVERY_SERVER=192.168.1.37:11811
    volumes:
      - "/dev/ttyGPS:/dev/ttyGPS"
      - "/dev/ttyTEENSY:/dev/ttyTEENSY"
      - "/dev/Arducam/:/dev/Arducam/"
    entrypoint: /home/robotics/Rover/entrypoint
    restart: "unless-stopped"
  uirover-interactive:
    image: "ethanholter/uirover"
    container_name: "rover-container"
    stdin_open: true # docker run -i
    tty: true 
    network_mode: "host"
    privileged: true
    environment:
      - ROS_DOMAIN_ID=69
      - ROS_DISCOVERY_SERVER=192.168.1.37:11811
    volumes:
      - "/dev/ttyGPS:/dev/ttyGPS"
      - "/dev/ttyTEENSY:/dev/ttyTEENSY"
      - "/dev/Arducam/:/dev/Arducam/"

# https://superuser.com/questions/360336/differentiate-between-identical-usb-devices-on-linux

# sudo docker compose -f docker/compose.yml run rover
