name: uirover

services:
  camera_pipeline:
    image: "ghcr.io/roboticsatiowa/camera_pipeline:latest"
    build: 
      context: ..
      dockerfile: ./docker/camera_pipeline/Dockerfile
    container_name: "camera_pipeline"
    environment:
      - ROS_DOMAIN_ID=1
    volumes:
      - "/dev/Arducam/:/dev/Arducam/"
    restart: "unless-stopped"
    entrypoint: /rover/entrypoint

  zed_f9p:
    image: "ghcr.io/roboticsatiowa/zed_f9p:latest"
    build: 
      context: ..
      dockerfile: ./docker/zed_f9p/Dockerfile
    container_name: "zed_f9p_gps"
    environment:
      - ROS_DOMAIN_ID=1
    volumes:
      - "/dev/ttyGPS:/dev/ttyGPS"
    restart: "unless-stopped"
    entrypoint: /rover/entrypoint

  teensy:
    image: "ghcr.io/roboticsatiowa/teensy:latest"
    build: 
      context: ..
      dockerfile: ./docker/teensy/Dockerfile
    container_name: "teensy_interface"
    environment:
      - ROS_DOMAIN_ID=1
    volumes:
      - "/dev/ttyTEENSY:/dev/ttyTEENSY"
    restart: "unless-stopped"
    entrypoint: /rover/entrypoint
  
  unitree_lidar:
    image: "ghcr.io/roboticsatiowa/unitree_lidar:latest"
    build: 
      context: ..
      dockerfile: ./docker/unitree_lidar/Dockerfile
    container_name: "unitree_lidar"
    environment:
      - ROS_DOMAIN_ID=1
    volumes:
      - "/dev/ttyLIDAR:/dev/ttyLIDAR"
    restart: "unless-stopped"
    entrypoint: /rover/entrypoint



  # uirover:
  #   image: "ethanholter/uirover"
  #   container_name: "rover-container"
  #   privileged: true
  #   environment:
  #     - ROS_DOMAIN_ID=69
  #   volumes:
  #     - "/dev/ttyGPS:/dev/ttyGPS"
  #     - "/dev/ttyTEENSY:/dev/ttyTEENSY"
  #     - "/dev/Arducam/:/dev/Arducam/"
  #   entrypoint: /home/robotics/Rover/entrypoint
  #   restart: "unless-stopped"
  # uirover-interactive:
  #   image: "ethanholter/uirover"
  #   container_name: "rover-container"
  #   stdin_open: true # docker run -i
  #   tty: true 
  #   network_mode: "host"
  #   privileged: true
  #   environment:
  #     - ROS_DOMAIN_ID=69
  #   volumes:
  #     - "/dev/ttyGPS:/dev/ttyGPS"
  #     - "/dev/ttyTEENSY:/dev/ttyTEENSY"
  #     - "/dev/Arducam/:/dev/Arducam/"

# https://superuser.com/questions/360336/differentiate-between-identical-usb-devices-on-linux

# sudo docker compose -f docker/compose.yml run rover
