services:
  rover:
    image: "rover"
    build: ..
    stdin_open: true  # Run in interactive mode. Not necessary for the rover, but useful for debugging
    tty: true         # ^^^
    network_mode: "host"
    privileged: true
    ports:
      - "24650-24651" # Using DOMAIN_ID=69 calculated here: https://docs.ros.org/en/galactic/Concepts/About-Domain-ID.html
      - "24660-24661"
    # devices:
      # - "/dev/ttyACM0:/dev/ttyACM0:ro" # Allow the container to access the Serial USB
      # - "/dev/ttyUSB0:/dev/ttyUSB0" # Allow the container to access the USB port
    environment:
      - ROS_DOMAIN_ID=69

# sudo docker compose -f docker/compose.yml run rover