# syntax=docker/dockerfile:1.7-labs

FROM ros:humble-ros-core-jammy

# use bash instead of sh. allows us to use 'source' command.
SHELL ["/bin/bash", "-c"]

# setup robotics user
RUN apt-get update -y && apt-get upgrade -y
RUN yes | apt-get install sudo
RUN apt install git python3-venv python3-rosdep2 python3-colcon-common-extensions ros-humble-rosbag2 python3-serial ros-humble-usb-cam -y
RUN echo "robotics ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers.d/local
RUN groupadd robotics
RUN useradd -rm -d /home/robotics -s /bin/bash -g robotics -G sudo robotics
RUN chown -R robotics:robotics /home/robotics
RUN usermod -aG dialout robotics

USER robotics
WORKDIR /home/robotics/Rover

# setup user environment
RUN touch "${HOME}/.bashrc"
RUN echo "source /opt/ros/humble/setup.bash" >> "${HOME}/.bashrc"
RUN echo "source ${HOME}/Rover/install/setup.bash" >> "${HOME}/.bashrc"

# setup rover repo
ADD ./bin ./bin 
ADD ./install.sh ./install.sh
ADD ./src ./src
RUN source install.sh -y
WORKDIR /home/robotics