#!/usr/bin/env bash
set -eo pipefail
shopt -s globstar nullglob

WS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." &> /dev/null && pwd )" # workspace directory

# check if --debug flag is passed
if [[ " $* " == *" --debug "* ]]; then
    DEBUG=1
else
    DEBUG=0
fi

# colcon has a very weird cli so instead we manually concatenate all the logs in the event of a failure.
# This results in a much more readable output.
function print_stderr_logs () {
    for file in $WS_DIR/log/latest/**/stderr.log;
    do
        # check if file is empty
        if [ ! -s "$file" ]; then
            continue
        fi
        echo
        echo
        echo "ERROR $file:"
        cat "$file"
    done
}

# Auto detect and install mandatory colcon packages if not already installed
if apt -qq list python3-colcon-common-extensions 2> /dev/null | grep -q installed; then
    echo "colcon-common-extensions is already installed"
else
    echo "Installing colcon-common-extensions"
    sudo apt update && sudo apt install -y python3-colcon-common-extensions
fi
if apt -qq list python3-colcon-mixin 2> /dev/null | grep -q installed; then
    echo "colcon-mixin is already installed"
else
    echo "Installing colcon-mixin"
    sudo apt update && sudo apt install -y python3-colcon-mixin
fi
MIXIN_URL="https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml"
if ! colcon mixin list 2>/dev/null | grep -q "$MIXIN_URL"; then
    colcon mixin add default "$MIXIN_URL"
fi

# desktop_notification- console_stderr- disable annoying features of colcon
# --continue-on-error continues building other packages even if one fails
# --parallel-workers 0 uses all available CPU cores
# --symlink-install symlinks files so we don't have to rebuild after every change
# --mixin compile-commands generates WS_DIR/build/compile_commands.json for vscode and other IDEs
COLCON_ARGS="--mixin compile-commands \
--continue-on-error \
--parallel-workers 0 \
--symlink-install \
--event-handlers desktop_notification-"

if [ "$DEBUG" -eq 1 ]; then
    COLCON_ARGS+=" --cmake-args -DCMAKE_BUILD_TYPE=Debug"
fi

(cd $WS_DIR && colcon build $COLCON_ARGS || print_stderr_logs)

# Append custom setup logic to setup.bash

cat >> "${WS_DIR}/install/setup.bash" <<'EOF'

# ===============================================
#        START OF CUSTOM GENERATED CODE
#       Generated by tools/ros/build.sh
# ===============================================

export RCUTILS_COLORIZED_OUTPUT=1
export ROS_DOMAIN_ID=0
export ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
export RMW_IMPLEMENTATION=rmw_zenoh_cpp
EOF

echo 'if [ -z "${ZENOH_ROUTER_CONFIG_URI+x}" ]; then' >> "${WS_DIR}/install/setup.bash"
echo "    export ZENOH_ROUTER_CONFIG_URI=\"$WS_DIR/zenoh_basestation.config.json5\"" >> "${WS_DIR}/install/setup.bash"
echo "fi" >> "${WS_DIR}/install/setup.bash" 