<?xml version="1.0"?>
<robot name="uirover" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- IMPORTS -->
  <xacro:include filename="$(find uirover_description)/xacro/utility_macros.xacro" />
  <xacro:include filename="$(find uirover_description)/xacro/properties.xacro" />

  <!-- BASE LINK -->
  <link name="base_link" />

  <!-- CHASSIS -->
  <link name="chassis">
  <visual>
    <origin xyz="0.0 0.21 0.0" rpy="${pi/2} 0.0 0.0"/>
    <geometry>
      <mesh filename="file://$(find uirover_description)/dae/chassis.dae"/>
    </geometry>
  </visual>
  </link>
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link" />
    <child link="chassis" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <!--L SUSPENSIONS-->
  <link name="l_suspension">
    <visual>
    <origin xyz="-0.085 -0.02 -0.06" rpy="${pi/2} 0.0 0.0"/>
    <geometry>
      <mesh filename="file://$(find uirover_description)/dae/suspension.dae"/>
    </geometry>
  </visual>
  </link>
  <joint name="l_suspension" type="fixed">
    <parent link="chassis" />
    <child link="l_suspension" />
    <origin xyz="0.35 0.28 0.1" rpy="0 0 0" />
  </joint>

  <!--R SUSPENSIONS-->
  <link name="r_suspension">
    <visual>
    <origin xyz="-0.085 -0.02 -0.06" rpy="${pi/2} 0.0 0.0"/>
    <geometry>
      <mesh filename="file://$(find uirover_description)/dae/suspension.dae"/>
    </geometry>
  </visual>
  </link>
  <joint name="r_suspension" type="fixed">
    <parent link="chassis" />
    <child link="r_suspension" />
    <origin xyz="0.35 -0.28 0.1" rpy="0 0 0" />
  </joint>

  <!-- SWIVEL JOINTS -->
  <xacro:wheel_swivel name="fl_swivel" x="${chassis_length/2.5+wheel_spacing}" y="${wheel_distance_side}" z="${-suspension_height-(chassis_height/2)}" />
  <xacro:wheel_swivel name="fr_swivel" x="${chassis_length/2.5+wheel_spacing}" y="${-wheel_distance_side}" z="${-suspension_height-(chassis_height/2)}" />
  <xacro:wheel_swivel name="bl_swivel" x="${chassis_length/2.5-wheel_spacing}" y="${wheel_distance_side}" z="${-suspension_height-(chassis_height/2)}" />
  <xacro:wheel_swivel name="br_swivel" x="${chassis_length/2.5-wheel_spacing}" y="${-wheel_distance_side}" z="${-suspension_height-(chassis_height/2)}" />

  <!-- WHEELS -->
  <xacro:wheel name="fl_wheel" x="0" y="0" z ="0" parent="fl_swivel" />
  <xacro:wheel name="fr_wheel" x="0" y="0" z ="0" parent="fr_swivel" />
  <xacro:wheel name="ml_wheel" x="${chassis_length/2.5}" y="${wheel_distance_side}" z="${-suspension_height-(chassis_height/2)}" parent="chassis" />
  <xacro:wheel name="mr_wheel" x="${chassis_length/2.5}" y="${-wheel_distance_side}" z="${-suspension_height-(chassis_height/2)}" parent="chassis"/>
  <xacro:wheel name="bl_wheel" x="0" y="0" z ="0" parent="bl_swivel" />
  <xacro:wheel name="br_wheel" x="0" y="0" z ="0" parent="br_swivel" />

  <!-- Robot Footprint -->
  <!-- This is needed for nav libraries. Its the 2D top-down profile of the robot. Makes for simpler collision detection. -->
  <link name="base_footprint" />
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_footprint" />
    <origin xyz="0.0 0.0 ${-0.3-chassis_height/2}" rpy="0 0 0" />
  </joint> 


</robot>