/**/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/diff_drive_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["fl_wheel_joint", "ml_wheel_joint", "bl_wheel_joint"]
    right_wheel_names: ["fr_wheel_joint", "mr_wheel_joint", "br_wheel_joint"]

    wheel_separation: 0.7493
    wheels_per_side: 3
    wheel_radius: 0.01143

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    # http://wiki.ros.org/diff_drive_controller#Skid_steer    covariance values ripped from the skid steer controller example
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 0.25
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: .NAN

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 1.0
    angular.z.max_acceleration: 1.0
    angular.z.max_jerk: .NAN