/**/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/diff_drive_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["fl_wheel_joint", "ml_wheel_joint", "bl_wheel_joint"]
    right_wheel_names: ["fr_wheel_joint", "mr_wheel_joint", "br_wheel_joint"]

    wheel_separation: 0.7493
    wheels_per_side: 3
    wheel_radius: 0.01143

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    position_feedback: false
    open_loop: true
    enable_odom_tf: false

    cmd_vel_timeout: 0.5 # seconds
    # publish_limited_velocity: false
    # velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.max_velocity: .NAN
    linear.x.max_acceleration: .NAN
    linear.x.max_jerk: .NAN

    angular.z.max_velocity: .NAN
    angular.z.max_acceleration: .NAN
    angular.z.max_jerk: .NAN